# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest  
  
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: 🔨 Build Project
        run: bundler exec nanoc

      - name: 📂 Sync files
        run: sshpass -p "${{secrets.PASSWORD}}" scp -r ./output ${{secrets.USER}}@${{secrets.SERVER}}:${{secrets.SERVERDIR}}
